# vim: ft=zsh fenc=utf-8

# Options
# http://zsh.sourceforge.net/Doc/Release/Options.html

# show options
# set -o

# Autoload {{{
# color
autoload -Uz colors && colors

# Run completions
autoload -Uz compinit && compinit
# }}}

# Changing Directories{{{
# Easy way to cd without cd command.
setopt AUTO_CD

# Make cd push the old directory onto the directory stack.
setopt AUTO_PUSHD

# Try to expand the expression as if it were preceded by a ~
setopt CDABLE_VARS

# Do not push multiple copies of the same directory onto the directory stack.
setopt PUSHD_IGNORE_DUPS
# }}}

# Completion {{{
setopt ALWAYS_TO_END
# setopt AUTO_LIST
setopt AUTO_MENU
setopt AUTO_NAME_DIRS
setopt AUTO_PARAM_KEYS
unsetopt AUTO_PARAM_SLASH
unsetopt AUTO_REMOVE_SLASH

# complete word 
setopt COMPLETE_IN_WORD

# setopt GLOB_COMPLETE

# no path hashed.
# unsetopt HASH_LIST_ALL

# no beep sound.
unsetopt NO_BEEP

setopt LIST_PACKED
setopt LIST_ROWS_FIRST
setopt MENU_COMPLETE
# }}}

# Expansion and Globbing {{{
# enable to use ~ ^ #.
setopt EXTENDED_GLOB
# setopt GLOB_SUBST

# setopt IGNORE_BRACES
# setopt IGNORE_CLOSE_BRACES

# add / if dir matched.
setopt MARK_DIRS

# no multi-byte
# unsetopt MULTIBYTE

# setopt NUMERIC_GLOB_SORT

# ksh / sh likes
# setopt SH_GLOB

# Print a warning message when an existing prarmeter from an enclosing function scope, or global.
# setopt WARN_CREATE_GLOBAL
# }}}

# History {{{
# extend history
HISTFILE=~/.zsh_history
HISTSIZE=999999
SAVEHIST=999999

# extend history
setopt EXTENDED_HISTORY
unsetopt HIST_BEEP
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_NO_FUNCTIONS
setopt HIST_NO_STORE
setopt HIST_REDUCE_BLANKS
setopt HIST_SAVE_NO_DUPS
setopt HIST_VERIFY
setopt INC_APPEND_HISTORY
setopt INC_APPEND_HISTORY_TIME
setopt SHARE_HISTORY
# }}}

# Input/Output {{{
# spell check
setopt CORRECT

# spell check all
setopt CORRECT_ALL

setopt IGNORE_EOF
setopt INTERACTIVE_COMMENTS
setopt RM_STAR_SILENT
setopt RM_STAR_WAIT
# }}}

# Job Control {{{
setopt MONITOR
setopt NOTIFY
setopt POSIX_JOBS
# }}}

# Prompting {{{
setopt PROMPT_SUBST
# }}}

# Scripts and Functions {{{
# array index start from 0
# setopt KSHARRAYS
# }}}

# Zsh Line Editor {{{
unsetopt BEEP
# setopt COMBINING_CHARS
setopt VI
setopt ZLE
# }}}

# Keybinding {{{
# use vi keybinding
# bindkey -v
# }}}

# zstyle {{{

# }}}

# Remove duplicate path.
typeset -U path cdpath fpath manpath
